### ISSUE TITLE
Bootable?

### ISSUE THREAD

**Issue by ylluminate** [openzfsonosx/zfs#243] opened 2014-10-24 20:06 UTC
Has any thought or effort yet gone into making this bootable?  I realize that there are a few more things to work through first to make sure that it is usable as a first class FS citizen on OS X, but I thought it might be worth starting to have some dialogue about it as I think most of us are growing tired of the potentiality of HFS+ corruptions (I'm repairing 3 filesystems as I type this and thus my inspiration... :smiling_imp: )

**Comment by yangm97** [comment] 2015-01-06 14:57
+1

**Comment by seanlinsley** [comment] 2015-01-06 16:32
I'd add $400

**Comment by hoondi** [comment] 2015-09-27 00:45
This has been quiet for a while now... 
Managed any further progress Evansus? 

Where's your pledge on BountySource seanlinsley?  ;)) (https://www.bountysource.com/issues/5507056-bootable/backers)

**Comment by kernelOfTruth** [comment] 2015-09-27 05:24
This indeed would be interesting and quite nice to have :+1: 

CC:

@evansus

**Comment by ylluminate** [comment] 2016-05-05 18:46
@evansus any more effort on this front?

**Comment by evansus** [comment] 2016-06-18 02:17
Latest branch, just merged from master (1.5.2) and undergoing testing:
https://github.com/evansus/zfs-1/tree/ldi-boot

Have been running stable from this commit:
https://github.com/evansus/zfs-1/tree/6cdb95d40eaf7e5feb2f43341508d8c5743323f7

**Comment by yangm97** [comment] 2016-06-20 11:30
@evansus care to share a video of it running?

**Comment by evansus** [comment] 2016-06-20 19:14
@yangm97 So here's a screenshot booted from zvol, followed by a video on YouTube

<img width="969" alt="screen shot 2016-06-20 at 2 45 49 pm" src="https://cloud.githubusercontent.com/assets/2881843/16206440/7e324216-36f6-11e6-820f-33449b9c7ec1.png">

[YouTube video](https://youtu.be/qI6HTLZz0uI)

**Comment by ylluminate** [comment] 2016-06-20 19:24
That's remarkably good news. I cannot wait to do away with HFS+ altogether. We are in desperate need of this sooner than later and waiting for APFS is just not something I am looking forward to since we don't know the history behind it yet.

**Comment by talios** [comment] 2016-06-20 23:24
This is awesome.  One question that comes to mind - is this zvol case sensitive, or insensitive? I seem to recall reading years ago OSX didn't like using case sensitive HPF+ volumes for booting - not sure if that's changed.

**Comment by ilovezfs** [comment] 2016-06-21 01:52
It's irrelevant. Both are supported by Apple.

**Comment by ylluminate** [comment] 2016-06-23 16:55
@evansus how close are we to a PR so we can get a broader set of eyes on this?  Seems like perhaps this is ready for some wider testing...?

**Comment by ilovezfs** [comment] 2016-06-23 17:01
@ylluminate Given
https://github.com/openzfsonosx/zfs/commits/zfs_boot
https://openzfsonosx.org/wiki/ZFS_on_Boot

@lundman and @evansus probably need to do a little "chatting" about that before we're in PR/testing territory.

@evansus Does this method require SIP to be disabled?

**Comment by rottegift** [comment] 2016-07-10 10:07
I've been living for a day and a bit with my normal boot environments on datasets in ldi-boot branches, and am surprised at how well it just works.

A couple of things I've observed so far:

1/ Chrome and Chrome Canary both freak out with bazillions of messages like this:

```
Jul 10 10:37:35 cla Google Chrome Helper[11630]: Critical failure: the LastResort font is unavailable.
```

I can reproduce this easily (in guest account on fresh install, even), so I suspect @lundman or @evansus could as well.

Today's plan is to try it in a bootable jhfs-containing zvol; I expect it will just work, and will comment here only if it does not.   

Other browsers and apps are fine, no font problems at all, no rendering issues.   So Chrome is doing something weird.

(Aside: cloning, using a checksum that allows nopwrite, and strategic use of rsync -c (checksum compare) makes for extremely efficient storage of different OS X boot environments; I have six on a mirrored rpool of two 256GB SSDs and still have space to drop in a zvol for testing).

I haven't yet found any other application or use problems.   Even Server.app is mostly happy.

Less importantly than figuring out why Chrome is breaking (and fixing it if possible):

2/ It'd be really nice if the root partition would also appear under /Volumes like native HFS boot partitions do.   (e.g. / is also mounted and accessible from /Volumes/startupvolumename).

I think this is part of why SuperDuper! and CCC fail to offer the boot volume as a backup source.

3/ It'd be nice to be able to choose a zvol to boot from as easily as setting the bootfs pool property (or even exactly by setting bootfs=pool/zvol[/gpt-partition]).

**Comment by ilovezfs** [comment] 2016-07-10 10:13
>surprised at how well it just works.

Anyone reading that needs to bear in mind the superhuman and pathological alpha-tolerance rottegift's immune system can handle due to years of abuse.

**Comment by evansus** [comment] 2016-07-10 15:11
@rottegift zvol should work fine, have been using zvol boot for quite some time myself. Just be sure to

1) clear the bootfs using `zpool set bootfs='' poolname` (two single quotes)
2) put the Root UUID from the jhfs+ volume into the Boot.plist
3) zfs_boot=poolname in Kernel Flags, although it could specify the zvol name here if you’d like.

Unfortunately 'bootfs' can only be set to a valid dataset (by object id) so selecting a zvol is not an option (nor adding the partition after). Even if bootfs were a string and we could do that, it might have compatibility problems with other platforms.

But as stated in 3) we could specify the full zvol name in "zfs_boot" in the Kernel Flags, and at boot time present the zvol to the OS as the boot-uuid-media. Then the Root UUID would not even need to match exactly, the name would be enough. To be clear, right now it doesn't make a different if you put "poolname" or "poolname/zvol", it will just import poolname - but it could be enhanced to do this.

**Comment by evansus** [comment] 2016-07-10 15:44
@ilovezfs short answer: Yes, SIP must be disabled, since you must compile your own kexts.
Long answer: I have booted with SIP enabled and it does work, but at that point kextcache will update your boot helper and remove the unsigned ZFS kexts (!!). So again yes, SIP must be disabled, but it does not directly *prevent* zfs boot.

**Comment by ilovezfs** [comment] 2016-07-10 15:45
So hopefully with signed kexts it will behave itself.

**Comment by evansus** [comment] 2016-07-11 17:37
Update: it turns out that when booting with SIP enabled, the zfs, spl, and KernelExports are still allowed to be linked by kextcache since they are loaded and active. So that seems to be a non issue for now.

**Comment by ylluminate** [comment] 2016-07-17 06:20
@rottegift really excited to hear your results there. How's it going after what you noted you were going to try? Any resolution with Chrome or have you hit any other issues?

I'd like to chat sometime as I'm about to go full ZFS myself I believe within the coming week or so.

@lundman you ever get past the `PVS vs ZFS - not a staged path` email from 25 May? I ask this in the same breath here since I think HFS compat is critical to the bootability issue as well.

**Comment by ilovezfs** [comment] 2016-07-17 06:28
I would strongly suggest users not be switching to this for production systems any time soon, nor for "it's not really production because I'm a home user so that doesn't really count does it?" when it is indeed production insofar as it's a system you rely a daily either a home workstation or home server. You've been warned.

**Comment by ilovezfs** [comment] 2016-07-17 06:30
Also, most of the discussion in this issue belongs in the forum since it's not actually about the code.

**Comment by ylluminate** [comment] 2016-07-18 15:15
@ilovezfs I concur, I've simply been carrying on this discussion here for the benefit of the Hackintosh community that has recently noted this discussion and the value of having a bootable ZFS to minimize panics, etc.

**Comment by ilovezfs** [comment] 2016-07-18 15:17
What's a Hackintosh? :see_no_evil:

**Comment by JMoVS** [comment] 2019-10-06 21:27
ZFS on Boot (both with HFS and native zFS) has been a thing for a while now

**Closed by JMoVS** 2019-10-06 21:27 UTC
