### ISSUE TITLE
Issues with git on ZFS

### ISSUE THREAD

**Issue by Licenser** [openzfsonosx/zfs#298] opened 2015-04-13 11:21 UTC
Hi,
I've run into some trouble with using git on ZFS on OS X. The basic workflow of the problem is:

```bash
$ git checkout branch-a
$ echo "using -a -m is bad behavior" >> README.md #(edit a file)
$ git commit -a -m "I shouldn't do this"
$ git checkout branch-b
$ git merge branch-a
#=> you have uncommitted changes in your branch aborting merge
```

This does not 'always' happen just sometimes which makes it quite hard to track, stashing the `branch-b` and being told "nothing to stash" works around it.

Another thing I saw which seems related is that some files could not be opened correctly leading to this bug: https://github.com/arekinath/e2qc/issues/4#issuecomment-92313505 which was solved by opening and closing the .c and .h files in vim.

To my setup:
```
$ zfs list
NAME                       USED  AVAIL  REFER  MOUNTPOINT
tank                      11.5G  81.4G   504K  /Volumes/tank
tank/Documents             504K  81.4G   504K  /Volumes/tank/Documents
tank/Projects             11.4G  81.4G  8.12M  /Users/heinz/Projects
tank/Projects/Other       4.12G  81.4G  4.12G  /Users/heinz/Projects/Other
tank/Projects/dalmatiner   608M  81.4G   608M  /Users/heinz/Projects/dalmatiner
tank/Projects/fifo        5.46G  81.4G  5.46G  /Users/heinz/Projects/fifo

$ zpool status
  pool: tank
 state: ONLINE
  scan: scrub repaired 0 in 0h0m with 0 errors on Mon Apr 13 13:03:38 2015
config:

	NAME        STATE     READ WRITE CKSUM
	tank        ONLINE       0     0     0
	  disk0s4   ONLINE       0     0     0

errors: No known data errors
``` 

I'm copying my project folder off off zfs for now but will leave the ZFS version for debugging for now. If there are any pointers how to get to the bottom of this it'd be incredible welcome.

**Comment by ilovezfs** [comment] 2015-04-13 11:25
Do you have casesensitivity=sensitive or insensitive?

**Comment by Licenser** [comment] 2015-04-13 11:30
It is set to sensitive

for completness (sorry I forgot that):
```
$ zpool get all tank
NAME  PROPERTY                    VALUE                       SOURCE
tank  size                        93G                         -
tank  capacity                    10%                         -
tank  altroot                     -                           default
tank  health                      ONLINE                      -
tank  guid                        2240792128651633420         default
tank  version                     -                           default
tank  bootfs                      -                           default
tank  delegation                  on                          default
tank  autoreplace                 off                         default
tank  cachefile                   -                           default
tank  failmode                    wait                        default
tank  listsnapshots               off                         default
tank  autoexpand                  off                         default
tank  dedupditto                  0                           default
tank  dedupratio                  1.47x                       -
tank  free                        82.8G                       -
tank  allocated                   10.2G                       -
tank  readonly                    off                         -
tank  ashift                      12                          local
tank  comment                     -                           default
tank  expandsize                  -                           -
tank  freeing                     0                           default
tank  fragmentation               7%                          -
tank  leaked                      0                           default
tank  feature@async_destroy       enabled                     local
tank  feature@empty_bpobj         active                      local
tank  feature@lz4_compress        active                      local
tank  feature@spacemap_histogram  active                      local
tank  feature@enabled_txg         active                      local
tank  feature@hole_birth          active                      local
tank  feature@extensible_dataset  enabled                     local
tank  feature@embedded_data       active                      local
tank  feature@bookmarks           enabled                     local

$ zfs get all tank/Projects/fifo
NAME                PROPERTY               VALUE                       SOURCE
tank/Projects/fifo  type                   filesystem                  -
tank/Projects/fifo  creation               Fri Mar 27  7:48 2015       -
tank/Projects/fifo  used                   5.46G                       -
tank/Projects/fifo  available              81.4G                       -
tank/Projects/fifo  referenced             5.46G                       -
tank/Projects/fifo  compressratio          1.49x                       -
tank/Projects/fifo  mounted                yes                         -
tank/Projects/fifo  quota                  none                        default
tank/Projects/fifo  reservation            none                        default
tank/Projects/fifo  recordsize             128K                        default
tank/Projects/fifo  mountpoint             /Users/heinz/Projects/fifo  inherited from tank/Projects
tank/Projects/fifo  sharenfs               off                         default
tank/Projects/fifo  checksum               on                          default
tank/Projects/fifo  compression            lz4                         inherited from tank/Projects
tank/Projects/fifo  atime                  on                          default
tank/Projects/fifo  devices                on                          default
tank/Projects/fifo  exec                   on                          default
tank/Projects/fifo  setuid                 on                          default
tank/Projects/fifo  readonly               off                         default
tank/Projects/fifo  zoned                  off                         default
tank/Projects/fifo  snapdir                hidden                      default
tank/Projects/fifo  aclmode                discard                     default
tank/Projects/fifo  aclinherit             restricted                  default
tank/Projects/fifo  canmount               on                          default
tank/Projects/fifo  xattr                  on                          default
tank/Projects/fifo  copies                 1                           default
tank/Projects/fifo  version                5                           -
tank/Projects/fifo  utf8only               off                         -
tank/Projects/fifo  normalization          none                        -
tank/Projects/fifo  casesensitivity        sensitive                   -
tank/Projects/fifo  vscan                  off                         default
tank/Projects/fifo  nbmand                 off                         default
tank/Projects/fifo  sharesmb               off                         default
tank/Projects/fifo  refquota               none                        default
tank/Projects/fifo  refreservation         none                        default
tank/Projects/fifo  primarycache           all                         default
tank/Projects/fifo  secondarycache         all                         default
tank/Projects/fifo  usedbysnapshots        0                           -
tank/Projects/fifo  usedbydataset          5.46G                       -
tank/Projects/fifo  usedbychildren         0                           -
tank/Projects/fifo  usedbyrefreservation   0                           -
tank/Projects/fifo  logbias                latency                     default
tank/Projects/fifo  dedup                  off                         default
tank/Projects/fifo  mlslabel               none                        default
tank/Projects/fifo  sync                   standard                    default
tank/Projects/fifo  refcompressratio       1.49x                       -
tank/Projects/fifo  written                5.46G                       -
tank/Projects/fifo  logicalused            6.71G                       -
tank/Projects/fifo  logicalreferenced      6.71G                       -
tank/Projects/fifo  snapdev                hidden                      default
tank/Projects/fifo  com.apple.browse       on                          default
tank/Projects/fifo  com.apple.ignoreowner  off                         default
tank/Projects/fifo  com.apple.mimic_hfs    off                         default
tank/Projects/fifo  redundant_metadata     all                         default
tank/Projects/fifo  overlay                off                         default
```

**Comment by ilovezfs** [comment] 2015-04-13 13:08
Please check if it also happens with insensitive. Note that the property can only be set at the time the dataset is created. For example,

```
zpool create -o ... -O ... -O casesensitivity=insensitive ...
```
or if you want to use the same pool,
```
zfs create -o casesensitivity=insensitive tank/foo
```

**Comment by Licenser** [comment] 2015-04-13 15:22
It does show the same behavior with case insensitive. I've managed to boil down the issue to a (somewhat) simple case:

```bash
$ git clone git://github.com/arekinath/e2qc.git
Cloning into 'e2qc'...
remote: Counting objects: 160, done.
remote: Total 160 (delta 0), reused 0 (delta 0), pack-reused 160
Receiving objects: 100% (160/160), 63.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (69/69), done.
Checking connectivity... done.
$ gcc e2qc/c_src/nif.c
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -cc1 -triple x86_64-apple-macosx10.10.0 -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name nif.c -mrelocation-model pic -pic-level 2 -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu core2 -target-linker-version 242 -dwarf-column-info -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0 -fdebug-compilation-dir /Volumes/tank/foo -ferror-limit 19 -fmessage-length 272 -stack-protector 1 -mstackrealign -fblocks -fobjc-runtime=macosx-10.10.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/cq/y3k8yt6s015gr90lf06ss7lw0000gn/T/nif-096133.o -x c e2qc/c_src/nif.c
1.	<unknown> parser at unknown location
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: error: unable to execute command: Segmentation fault: 11
clang: note: diagnostic msg: Error generating preprocessed source(s).
```

The same commands executed on the normal HFS+ (I think?) volume don't segfault (they fail because of  a missing -I but that is not a issue.

**Comment by ilovezfs** [comment] 2015-04-13 15:39
What is the output of

```
sysctl -a | grep kext_
```

**Comment by Licenser** [comment] 2015-04-13 15:44
It's:

```
$ sysctl -a | grep kext_
spl.kext_version: 1.3.1-1.1
zfs.kext_version: 1.3.1-1.1
```

**Comment by ilovezfs** [comment] 2015-04-13 16:16
You need to upgrade to r2:
https://openzfsonosx.org/wiki/Downloads#1.3.1-r2

This was already fixed: https://github.com/openzfsonosx/zfs/commit/bf47fea3142ead6b9df8e666d4e8c03973752ac5

**Comment by ilovezfs** [comment] 2015-04-13 16:17
Duplicate of https://github.com/openzfsonosx/zfs/issues/295

**Closed by ilovezfs** 2015-04-13 16:17 UTC
Labels: duplicate

**Comment by Licenser** [comment] 2015-04-13 16:22
Indeed wonderful :) thank you!

**Comment by ilovezfs** [comment] 2015-04-13 16:23
@Licenser You're welcome. Thanks for updating your Twitter comment as well.
