### ISSUE TITLE
Crash loop on Yosemite 10.10.4

### ISSUE THREAD

**Issue by bacanol** [openzfsonosx/zfs#354] opened 2015-08-02 14:15 UTC
Hello!

I am trying to get OpenZFS running on my Yosemite 10.10.4 machine without success. If I install with the Installer (1.3.1-r2) or with the source installation following (https://openzfsonosx.org/wiki/Install#Initial_installation_from_source) I get kernel panic directly and the computer loops with startup and crash until I stop this. I was able to uninstall both versions with the Recovery Partition and some Terminal commands. 

Is OpenZFS compatible with 10.10.4 ? Am I missing a bit here?

Below you may find a bunch of kernel panic logs with some details I am not able to decrypt.

If I can help here with supplying more information, please go ahead.

Thank you and best regards,

Nico

---
Anonymous UUID:       07F485ED-ED47-B624-1B5B-9E4C0D1BA04E

Sun Aug  2 15:08:21 2015

*** Panic Report ***
panic(cpu 0 caller 0xffffff800c417cc2): Kernel trap at 0xffffff800c10e058, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x00007ff5d0c11260, CR3: 0x000000043b4bf065, CR4: 0x00000000003627e0
RAX: 0x00007ff5d0c11260, RBX: 0x0000000000000016, RCX: 0x0000000000000007, RDX: 0x0000000000000038
RSP: 0xffffff81f6efba38, RBP: 0xffffff81f6efba40, RSI: 0x00007ff5d0c11260, RDI: 0xffffff81fd5ffe30
R8:  0xffffff802cd2b840, R9:  0x0000000000000000, R10: 0x0000000000000000, R11: 0x0000000000000206
R12: 0xffffff81fd5ffe30, R13: 0x0000000080000000, R14: 0x00007ff5d0c11260, R15: 0x0000000000000038
RFL: 0x0000000000010202, RIP: 0xffffff800c10e058, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x00007ff5d0c11260, Error code: 0x0000000000000001, Fault CPU: 0x0 SMAP fault

Backtrace (CPU 0), Frame : Return Address
0xffffff81f6efb6e0 : 0xffffff800c32bda1 
0xffffff81f6efb760 : 0xffffff800c417cc2 
0xffffff81f6efb920 : 0xffffff800c434b73 
0xffffff81f6efb940 : 0xffffff800c10e058 
0xffffff81f6efba40 : 0xffffff7f8cb199a3 
0xffffff81f6efba90 : 0xffffff7f8cb19510 
0xffffff81f6efbb30 : 0xffffff800c581019 
0xffffff81f6efbb80 : 0xffffff800c56f856 
0xffffff81f6efbc10 : 0xffffff800c5646f3 
0xffffff81f6efbe00 : 0xffffff800c7aea1b 
0xffffff81f6efbe30 : 0xffffff800c7ed994 
0xffffff81f6efbf50 : 0xffffff800c84bc56 
0xffffff81f6efbfb0 : 0xffffff800c435376 
      Kernel Extensions in backtrace:
         net.lundman.zfs(1.3.1)[0A0974C1-DAF6-31E2-AC90-1DAFD34649D1]@0xffffff7f8caab000->0xffffff7f8cc59fff
            dependency: com.apple.iokit.IOStorageFamily(2.0)[76E50D45-C97B-3ED1-97C5-94E6E0EB4514]@0xffffff7f8ca47000
            dependency: net.lundman.spl(1.3.1)[C6AC8C88-D1A1-329A-B4BA-359F129DE859]@0xffffff7f8ca76000

BSD process name corresponding to current thread: zpool

Mac OS version:
14E46

Kernel version:
Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64
Kernel UUID: E3C26B2F-8B97-3F1D-B193-690F7E34F830
Kernel slide:     0x000000000c000000
Kernel text base: 0xffffff800c200000
__HIB  text base: 0xffffff800c100000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 16256242005
last loaded kext at 13340018816: org.virtualbox.kext.VBoxNetAdp	4.3.30 (addr 0xffffff7f8ebf3000, size 28672)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	4.3.30
org.virtualbox.kext.VBoxNetFlt	4.3.30
org.virtualbox.kext.VBoxUSB	4.3.30
org.virtualbox.kext.VBoxDrv	4.3.30
net.lundman.zfs	1.3.1
net.lundman.spl	1.3.1
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.ApplePlatformEnabler	2.2.0d4
com.apple.driver.AGPM	110.19.6
com.apple.driver.X86PlatformShim	1.0.0
com.apple.iokit.IOBluetoothSerialManager	4.3.5f8
com.apple.driver.AppleUSBCDC	4.3.3b1
com.apple.iokit.IOBluetoothUSBDFU	4.3.5f8
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleGraphicsDevicePolicy	3.7.7
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleHDAHardwareConfigDriver	272.18.1
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.AppleHDA	272.18.1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleThunderboltIP	2.0.2
com.apple.driver.AppleMuxControl	3.10.24
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleCameraInterface	5.36.0
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleBacklight	170.7.4
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.5f8
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleIntelBDWGraphics	10.0.6
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	10.0.6
com.apple.iokit.SCSITaskUserClient	3.7.5
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.CoreStorageFsck	471.30.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.iokit.IOAHCIPassThrough	1.0.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AppleTopCaseHIDEventDriver	67
com.apple.driver.AirPort.Brcm4360	930.37.3
com.apple.driver.AppleUSBXHCI	710.4.11
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	272.18.1
com.apple.kext.OSvKernDSPLib	1.15
com.apple.driver.AppleGraphicsControl	3.10.24
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.driver.AppleThunderboltEDMSink	4.0.3
com.apple.driver.AppleThunderboltDPOutAdapter	4.0.6
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.5f8
com.apple.iokit.IOBluetoothFamily	4.3.5f8
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleHDAController	272.18.1
com.apple.iokit.IOHDAFamily	272.18.1
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleIntelLpssUART	2.0.57
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.AppleGraphicsDeviceControl	3.10.24
com.apple.iokit.IOAcceleratorFamily2	156.16
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.driver.CoreStorage	471.30.1
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.driver.AppleThunderboltDPInAdapter	4.0.6
com.apple.driver.AppleThunderboltDPAdapterFamily	4.0.6
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.AppleHIDKeyboard	176.2
com.apple.driver.AppleHSSPIHIDDriver	41.3
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.driver.AppleThunderboltNHI	3.1.7
com.apple.iokit.IOThunderboltFamily	4.2.2
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.AppleHSSPISupport	41.3
com.apple.driver.AppleIntelLpssSpiController	2.0.57
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleIntelLpssI2C	2.0.57
com.apple.driver.AppleIntelLpssGspi	2.0.57
com.apple.driver.AppleIntelLpssDmac	2.0.57
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	397
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1

System Profile:
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.5f8 15969, 3 services, 27 devices, 1 incoming serial ports
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x02FE, 0x4544464232333241314D412D4A442D460000
USB Device: Internal Memory Card Reader
USB Device: Bluetooth USB Host Controller
Serial ATA Device: APPLE SSD SM0256G, 251 GB
Model: MacBookPro12,1, BootROM MBP121.0167.B07, 2 processors, Intel Core i5, 2.7 GHz, 16 GB, SMC 2.28f7
Network Service: Wi-Fi, AirPort, en0
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In

**Comment by ilovezfs** [comment] 2015-08-02 16:36
This is a duplicate of https://github.com/openzfsonosx/zfs/issues/288

Use the Yosemite version of 1.3.2-RC2 and the problem should go away:
https://openzfsonosx.org/forum/viewtopic.php?f=20&t=2262

Decoding the report I get:
```
$ xcrun atos -arch x86_64 -o zfs/module/zfs/zfs.kext/Contents/MacOS/zfs -l 0xffffff7f8caab000 0xffffff800c32bda1 0xffffff800c417cc2 0xffffff800c434b73 0xffffff800c10e058 0xffffff7f8cb199a3 0xffffff7f8cb19510 0xffffff800c581019 0xffffff800c56f856 0xffffff800c5646f3 0xffffff800c7aea1b 0xffffff800c7ed994 0xffffff800c84bc56 0xffffff800c435376
0xffffff800c32bda1
0xffffff800c417cc2
0xffffff800c434b73
0xffffff800c10e058
get_nvlist (in zfs) (zfs_ioctl.c:1201)
zfsdev_ioctl (in zfs) (zfs_ioctl.c:5742)
0xffffff800c581019
0xffffff800c56f856
0xffffff800c5646f3
0xffffff800c7aea1b
0xffffff800c7ed994
0xffffff800c84bc56
0xffffff800c435376
```

**Closed by ilovezfs** 2015-08-02 16:36 UTC
Labels: duplicate
