### ISSUE TITLE
Disk corruption with 1.7.1

### ISSUE THREAD

**Issue by kv63** [openzfsonosx/zfs#631] opened 2018-03-18 13:23 UTC
The latest release has problems with disk corruption.

This became noticeable on writes to large files (VMDK vmware files). 

After large numbers of writes (300MB+), there are file system errors that need to repaired.

Downgrading to 1.6.1 resolves these problems.  

See link to forum comments.  This issue has been confirmed by a second user:

https://openzfsonosx.org/forum/viewtopic.php?f=26&t=3149

**Comment by aabc123** [comment] 2018-03-19 06:05
Seems to be caused by commit 727b75735cd91c5c8201a3084243a234e1b868ec (Implement VNOP_ALLOCATE).  Removing that commit and the problem goes away.

Also, it only affects non-preallocated disks.  If you pre-allocate the virtual disks (either split or non-split), then you don't get the issue.

**Comment by capcasady** [comment] 2018-03-20 13:27
I have not seen this using 1.7.0

**Comment by as-com** [comment] 2018-03-20 13:32
I am running from Git from the commit before the 1.7.1 commit, and I have seen these same VMware errors. The filesize of the .vmware file also appears to be ridiculously large in Finder (like several hundred gigabytes, which is storage I don't have). However, the data in the VM seems to be fine...

**Comment by ilovezfs** [comment] 2018-03-24 20:54
Should be fixed in 1.7.2: https://openzfsonosx.org/wiki/Downloads#1.7.2

**Closed by ilovezfs** 2018-03-24 20:54 UTC
