### ISSUE TITLE
Time Machines shares hosted on zfs dont work under High Sierra

### ISSUE THREAD

**Issue by brendonhumphrey** [openzfsonosx/zfs#626] opened 2018-01-20 20:54 UTC
All HS clients now have the capability to create TM shares. Using the sharing tab, create a share, then right mouse click on the entry in the control panel, advanced, share as timemachine.

When that share is hosted on ZFS and a client computer attempts a backup it will report that the share does not have the required capabilities. Mimic on does not seem to help at this stage.

**Comment by lundman** [comment] 2018-01-26 00:34
Confirmed to work in branch issue116_lite

![screen shot 2018-01-26 at 0933 21 2](https://user-images.githubusercontent.com/637168/35419580-119b3b64-027c-11e8-880a-e7eb5d5c5e79.png)

**Comment by chrisr-diffblue** [comment] 2018-03-14 12:56
Hi @lundman - This issue is biting me at the moment, so I was just wondering what the status of issue116_lite is - any idea when it's likely to make it into master or a release? If there's anything I can help with I'd be happy to try (I'm a professional C/C++ developer by trade, mostly working on compilers and static analysis tools). It looks like issue116_lite needs a rebase, but what else is still needed?

**Comment by lundman** [comment] 2018-03-19 04:48
I have updated issue116_lite branch, and ran zfstester run on it. Feel free to give it a go and see if there is anything missing. I do want to merge it soon. You need to `make install` it so you get the /L/Filesystems/zfs.fs bundle. After that, the pool should get a `/dev/diskX` mount. And any datasets you change devdisk=on for should as well.

**Comment by chrisr-diffblue** [comment] 2018-03-19 09:29
Many thanks @lundman - that's awesome :-) I was about to start looking at rebasing it, so I'll go ahead and try it out and let you know how I get on :-)

**Comment by chrisr-diffblue** [comment] 2018-03-20 11:16
Update: Trying this out right now, and got an initial network time machine backup going to a ZFS hosted share at the moment, so far so good, but will update after fuller testing. A couple of things I've noted about `devdisk=on` so far though, which I'll raise issues for once I've had time to make some simpler reproducers:

1) I have two pools (one pool, is a striped pair of SSD's in a Thunderbolt enclosure, the other is a single spinning disk in a USB3 enclosure. Only the second pool is getting /dev/disk entries created for the root pool - there are no disk entries created for the first pool. I haven't tried setting devdisk on any other datasets below the root dataset on the first pool yet to see if that makes disk entries appear.

2) When doing `zfs rename` on a dataset that has `devdisk=on`, `name` field in the output of `diskutil list` for the associated /dev/disk entry seems to become blank. An export/import of the pool makes the names show up properly in the `diskutil` output again.

Looks great so far though, so many thanks!

**Comment by lundman** [comment] 2018-03-20 11:22
I'm reasonably sure that I did not implement it automatically remounting, when you change the value of devdisk. So you will need to manually `zfs umount` `zfs mount` if you change it (or, export/import, or reboot)

**Comment by chrisr-diffblue** [comment] 2018-03-20 14:04
Thanks for the extra info - that makes sense. I've also just figured out why I wasn't seeing a device entry for one of the pools - I'd set the root dataset on that pool to have a `mountpoint=none` as it was just holding a ZVOL, and that was causing the diskutil entry to have a blank name. I've now set a mountpoint and both pools are showing up in diskutil output with devices names :-)

**Comment by chrisr-diffblue** [comment] 2018-03-26 19:40
I noticed this has now been merged into master, so I've switched to using master to pick up the 1.7.2 corruption bug fix as well. All has been performing really well for me so far, so I'm looking forward to a 1.7.3 or 1.8 with this feature included :-) thanks again for your work on this - this has unlocked a major blocking point for me.

**Closed** 2019-03-10 10:35 UTC
