### ISSUE TITLE
Server does not allow to choose ZFS volume as a data destination drive (at least for Caching)

### ISSUE THREAD

**Issue by claunia** [openzfsonosx/zfs#282] opened 2015-02-24 22:14 UTC
O3X: 1.3.1-RC5
Mac OS X: 10.10.0
Server: 4

Cannot choose a ZFS volume as a data destination drive for Caching. They even don't appear listed. Have not tested other services.

**Comment by brendonhumphrey** [comment] 2015-02-27 09:26
Server only allows storage on hfs volumes. There is an experimental branch in the repository that allows zfs to identify itself as hfs. Once done, server allows selection of a zfs dataset as its storage area. Some limited testing of server has been done under this configuration, it seems that it generally works, some problems with LDAP start/stop, and mail server is non-functional right now.

We have not yet decided whether to merge this feature in for the upcoming release.

Cheers
Brendon

**Comment by rottegift** [comment] 2015-02-27 10:25
On 27 Feb 2015, at 09:26, brendonhumphrey <notifications@github.com> wrote:

> Server only allows storage on hfs volumes. There is an experimental branch in the repository that allows zfs to identify itself as hfs. Once done, server allows selection of a zfs dataset as its storage area. Some limited testing of server has been done under this configuration, it seems that it generally works, some problems with LDAP start/stop, and mail server is non-functional right now.

Specifically, postfix master fails a poll() system call on /Library/Server/Mail/Data/spool/public/cleanup (a fifo) when the whole of /Library/Server is on a zfs dataset with com.apple.mimic_hfs=on.        This happens whenever postfix is started.

The other issues are related to system shutdown at the CLI.

slapd suffers bdb corruptions (missing log file) when shutdown -r is used when /var/db/openldap is a zfs dataset (whatever the setting of sync and com.apple.mimic_hfs settings are).     It seems like slapd writes out a log file as it gets the final SIGHUP, but that log file never makes it to the dataset (or alternatively is never committed to the pool).

Some apps suffer similar database corruptions (missing final writes) in the face of shutdown -r when ~/Library/Saved Application State is a zfs dataset.   Again, fiddling with properties does not make a difference.   The most commonly affected application is Terminal.app, which loses windows and window-contents from time to time across reboots triggered by typing sudo shutdown -r into a Terminal window (or an iTerm2 window, or via ssh or whatever).

The slapd and Saved Application State missing writes are a bit worrisome, and do not happen when the directories are are on the (JHFS+) startup volume.

(I would of course wish people would duplicate this so it�s not just me :-) )

**Comment by lundman** [comment] 2015-02-27 10:39
This is interesting, so poll() fails, that is odd since we dont do anything there, BUT we do define fifo vnops which is interesting. 

bdb uses mmap, makes me worries that is still broken ;)

**Comment by rottegift** [comment] 2015-02-27 13:08
On 27 Feb 2015, at 10:39, Jorgen Lundman <notifications@github.com> wrote:

> This is interesting, so poll() fails, that is odd since we dont do anything there, BUT we do define fifo vnops which is interesting. 
> 
> bdb uses mmap, makes me worries that is still broken ;)
> 

As I said on IRC, http://stackoverflow.com/questions/22021253/poll-on-named-pipe-returns-with-pollhup-constantly-and-immediately has an example program in it that will fail if the pipename variable is set to a name inside an o3x zfs dataset.

(It works as is (just cc -o fifotest fifotest.c; fifotest), if /tmp is on the HFS+ startup volume;  it also works if the pipename is a target in a zvol formatted to HFS+).

**Comment by rottegift** [comment] 2015-02-27 13:13
On 27 Feb 2015, at 10:39, Jorgen Lundman <notifications@github.com> wrote:

> bdb uses mmap, makes me worries that is still broken ;)
> 
It seems to be wholly shutdown related; it works fine in normal use, or when arbitrary signals are sent to slapd.

Likewise, force quitting leads to ~/Library/Saved Application State having the right information to resume all the apps I’ve tested, but shutdown -r causes some of them to lose state (again, most often it’s Terminal.app or Google Chrome Canary, both of which have lots of windows and tabs and scroll backs and so forth to preserve at normal exit).

Is it possible the kext doesn’t receive some last second I/O during the shutdown process (e.g., after the GUI is gone and when launchd is signalling processes to die) ?

With slapd the problem is that when it gets the sigterm from launchd, the .log file that it wants to write out is not found in the dataset after a reboot; there’s no corruption of the stuff that was actually committed to the pool.

**Comment by lundman** [comment] 2015-03-02 01:13
b55918524db3a64afb60cac060cfe72e984d6614

Closes the original issue. Postfix was already dealt with, and BDB will be handled somewhere separately

**Closed by lundman** 2015-03-02 01:13 UTC

**Comment by rottegift** [comment] 2015-03-04 11:23
On 2 Mar 2015, at 01:13, Jorgen Lundman <notifications@github.com> wrote:

> Closed #282.
> 
> 
Also fixed: swupd_syncd into zfs datasets, which was discovered by finding 100GiB of software updates had been automagically downloaded overnight… :/
