### ISSUE TITLE
Cannot backup ZFS volumes via Time Machine

### ISSUE THREAD

**Issue by TheMacMini09** [openzfsonosx/zfs#335] opened 2015-06-21 00:10 UTC
As the title says. The volumes are automatically excluded in Time Machine, and attempting to remove them fails (select volumes, click "-", click "Save", click "Options..." volumes are back). I can't seem to find anything anywhere suggesting a fix (or that this is intended) - any help would be appreciated.

**Comment by brendonhumphrey** [comment] 2015-06-21 01:18
Duplicate of #66, this is a known issue. Thanks for the report.

**Closed by brendonhumphrey** 2015-06-21 01:18 UTC

**Comment by Fnuxus** [comment] 2020-04-16 14:41
> As the title says. The volumes are automatically excluded in Time Machine, and attempting to remove them fails (select volumes, click "-", click "Save", click "Options..." volumes are back). I can't seem to find anything anywhere suggesting a fix (or that this is intended) - any help would be appreciated.

See if https://openzfsonosx.org/forum/viewtopic.php?f=11&t=3408 works for you.
